name: Deploy to Vultr

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VULTR_IP }}
          username: root
          password: ${{ secrets.VULTR_PASSWORD }}
          script: |
            cd ageofhexes/ageofhexes-io
            git pull origin main
            npm install
            pm2 restart all